import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { services } from '../../data/content';
import Icon from '../Icon';
import Reveal from '../Reveal';
import { contact } from '../../utils/site';

export default function Services({ onSelectService }: { onSelectService: (service: string) => void }) {
  const [filter, setFilter] = useState('todos');
  return (<section className="solutions section" id="servicos"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow"><span className="section-index">01 /</span> NOSSOS SERVIÇOS</p><h2>Qual serviço sua<br/><span>empresa precisa?</span></h2></div><p>Da equipe de limpeza à entrega de uma obra, veja como podemos atender seu espaço.</p></Reveal><div className="filters" role="group" aria-label="Filtrar serviços">{[{id:'todos',label:'Todos os serviços'},{id:'empresarial',label:'Para empresas'},{id:'especializado',label:'Limpeza especializada'}].map(item=><button key={item.id} aria-pressed={filter===item.id} className={filter===item.id?'active':''} onClick={()=>setFilter(item.id)}>{item.label}<span>{item.id==='todos'?'05':item.id==='empresarial'?'02':'03'}</span></button>)}</div><motion.div layout className={`services filter-${filter}`}><AnimatePresence initial={false} mode="popLayout">{services.filter(s=>filter==='todos'||s.category===filter).map(s=><motion.article layout key={s.id} initial={false} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.25}} className={`service ${s.id==='terceirizacao'?'service-featured':''}`}><div className="service-top"><span className="service-number">{s.number}</span><Icon name={s.icon} size={s.id==='terceirizacao'?46:27}/></div><div className="service-content"><p className="eyebrow">{s.tag}</p><h3>{s.name}</h3><p>{s.text}</p>{s.details.length>0&&<ul>{s.details.map(detail=><li key={detail}><Icon name="check" size={16}/>{detail}</li>)}</ul>}</div><a href="#orcamento" className="service-link" aria-label={`Solicitar orçamento: ${s.name}`} onClick={()=>onSelectService(s.name)}><span>Pedir orçamento</span><span className="circle-arrow"><Icon name="arrow" size={20}/></span></a></motion.article>)}</AnimatePresence></motion.div><div className="solutions-bottom"><span>Precisa de ajuda para escolher?</span><a href={contact}>Conte sua necessidade pelo WhatsApp <Icon name="arrow" size={17}/></a></div></div></section>);
}
