import { useEffect, useState } from 'react';
import { motion, AnimatePresence, MotionConfig, useReducedMotion } from 'motion/react';
import QuoteForm from './components/QuoteForm';


import Icon from './components/Icon';
import { company } from './data/company';
const contact = company.whatsapp ? `https://wa.me/${company.whatsapp}?text=${encodeURIComponent('Olá! Quero solicitar um orçamento da Pratic Limp.')}` : '#orcamento';
const services = [
 {name:'Limpeza corporativa', tag:'PARA SUA EMPRESA', icon:'building', text:'Um ambiente bem cuidado para sua equipe trabalhar e seus clientes se sentirem bem. Planeje a limpeza de escritórios, comércios e espaços empresariais.', image:'photo-1497366754035-f200968a6e72', alt:'Escritório claro com mesas e plantas', type:'corporativo'},
 {name:'Limpeza de condomínios', tag:'PARA SEU CONDOMÍNIO', icon:'home', text:'Cuidado com os espaços que todos compartilham. Organize a conservação de halls, corredores e áreas comuns conforme a rotina do condomínio.', image:'photo-1600585154340-be6161a56a0c', alt:'Área externa de um imóvel com jardim', type:'corporativo'},
 {name:'Limpeza pós-obra', tag:'PARA UM NOVO COMEÇO', icon:'spark', text:'A obra termina. O cuidado começa. Solicite uma avaliação para remover resíduos e preparar o ambiente para a próxima etapa.', image:'photo-1600210492486-724fe5c67fb0', alt:'Sala ampla e iluminada com acabamentos claros', type:'especializado'},
 {name:'Terceirização de limpeza', tag:'PARA SUA OPERAÇÃO', icon:'people', text:'Mais tempo para o que faz seu negócio crescer. Converse sobre uma solução de mão de obra de limpeza alinhada ao seu espaço e à sua operação.', image:'photo-1497366811353-6870744d04b2', alt:'Ambiente de trabalho com mesas de reunião', type:'corporativo'},
];
const faq = [
 ['Como solicito um orçamento?', 'Conte o tipo de ambiente, a cidade e o serviço desejado no formulário abaixo. Você poderá revisar a mensagem e enviá-la à Pratic Limp para avaliar o escopo e receber uma proposta.'],
 ['O atendimento pode ser pontual ou recorrente?', 'Informe se precisa de uma limpeza pontual ou de uma rotina de conservação. A frequência, os horários e a disponibilidade serão definidos na proposta.'],
 ['Os produtos e equipamentos estão incluídos?', 'A inclusão de produtos, equipamentos e materiais deve ser definida no orçamento. Informe também superfícies delicadas ou restrições de produtos no seu ambiente.'],
 ['Quais cidades a Pratic Limp atende?', 'Informe sua cidade e seu bairro ao solicitar o orçamento. A equipe confirma a cobertura e a disponibilidade para o local antes da contratação.'],
 ['Como é definido o valor do serviço?', 'O orçamento depende do tipo de serviço, da área, das condições do espaço e da frequência desejada. Dependendo da necessidade, uma avaliação do local pode ser indicada.'],
];

export default function App({privacy=false}:{privacy?:boolean}) {
const [menuOpen,setMenuOpen]=useState(false);
const [filter,setFilter]=useState('todos');
const [selectedService,setSelectedService]=useState('');
const reduced=useReducedMotion();
useEffect(() => { const close=(e:KeyboardEvent)=> {if(e.key==='Escape')setMenuOpen(false)};document.addEventListener('keydown',close);return ()=>document.removeEventListener('keydown',close);},[]);
if(privacy) return (<main className="container legal"><a className="text-link" href="/">← Voltar para o site</a><h1 style={{fontSize:42,marginTop:45}}>Sua privacidade</h1><p>O formulário prepara uma mensagem no seu navegador. Este site não mantém uma base de solicitações e não envia os dados automaticamente. Ao continuar, você decide enviar a mensagem pelo aplicativo de contato indicado.</p><h2>Informações de contato</h2><p>Nome, telefone, cidade e detalhes do serviço são usados para compor o pedido de orçamento. Evite incluir dados sensíveis. O aplicativo de e-mail ou WhatsApp utilizado possui suas próprias práticas de privacidade.</p><h2>Recursos externos</h2><p>As imagens ilustrativas são carregadas do Unsplash e as fontes do Google Fonts. Essas conexões podem compartilhar dados técnicos, como endereço IP, com os respectivos provedores. Nenhum Google Analytics, Meta Pixel ou Hotjar está ativado nesta versão.</p><h2>Fale com a empresa</h2><p>Para dúvidas sobre seus dados ou para solicitar sua exclusão de conversas já enviadas, entre em contato pelo e-mail <a href={`mailto:${company.email}`}>{company.email}</a>.</p><p>Atualizado em 3 de outubro de 2026.</p></main>);
return <MotionConfig reducedMotion="user">
<a className="skip" href="#conteudo">Pular para o conteúdo</a>
<div className="topbar"><div className="container"><span>Limpeza e conservação para sua empresa e para você.</span><a href={company.phoneHref}><Icon name="phone" size={14}/>{company.phone}</a></div></div>
<header><div className="container nav"><a className="brand" href="#" aria-label="Pratic Limp — início"><span className="brand-mark"><Icon size={29}/></span><span>pratic<span className="brand-light">limp</span><small>LIMPEZA & CONSERVAÇÃO</small></span></a><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="menu" onClick={() => setMenuOpen(!menuOpen)}>Menu <span>☰</span></button><nav className={menuOpen ? "open" : ""} onClick={() => setMenuOpen(false)} id="menu" aria-label="Navegação principal"><a href="#servicos">Nossas soluções</a><a href="#sobre">A Pratic Limp</a><a href="#duvidas">Dúvidas frequentes</a></nav><a className="button button-small header-cta" href="#orcamento">Solicitar orçamento <Icon name="arrow" size={17}/></a></div></header>
<main id="conteudo">
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="dot"></span> CUIDADO QUE FAZ A DIFERENÇA</p><h1>Seu espaço<br/>bem cuidado.<br/><span>Sua rotina<br className="desktop-break"/> mais leve.</span></h1><p className="hero-description">Limpeza e conservação para empresas, condomínios e para você. Conte com a Pratic Limp para cuidar do ambiente enquanto você cuida do que importa.</p><div className="hero-actions"><a className="button" href="#orcamento">Solicitar meu orçamento <Icon name="arrow" size={19}/></a><a className="text-link" href="#servicos">Conheça as soluções <span>↗</span></a></div><div className="hero-notes"><span><Icon name="check" size={16}/> Proposta sob medida</span><span><Icon name="check" size={16}/> Contato direto</span></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85" width="900" height="1050" fetchPriority="high" alt="Escritório iluminado, organizado e cercado por plantas"/><div className="photo-shade"></div><span className="photo-label"><span className="dot"></span> MAIS CUIDADO EM CADA DETALHE</span><div className="visual-card"><span className="card-icon"><Icon name="shield" size={30}/></span><div><strong>Ambiente cuidado.<br/>Tranquilidade para você.</strong><small>Esse é o jeito Pratic Limp.</small></div><Icon name="spark" size={28}/></div><span className="vertical-label">PRATIC LIMP · LIMPEZA & CONSERVAÇÃO</span></div></div></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="audiences" aria-label="Ambientes atendidos"><div className="container"><p>Cada ambiente tem uma necessidade.<br/><strong>A sua também tem uma solução.</strong></p><span><Icon name="building"/> Empresas</span><span><Icon name="home"/> Condomínios</span><span><Icon name="spark"/> Residências</span><span><Icon name="people"/> Espaços comerciais</span></div></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="section container" id="servicos"><div className="section-heading"><div><p className="eyebrow">NOSSAS SOLUÇÕES</p><h2>O cuidado certo.<br/>Para o seu espaço.</h2></div><p>Da rotina da sua empresa a um novo começo.<br/>Encontre a solução que combina com você.</p></div><div className="filters" role="group" aria-label="Filtrar serviços">{[{id:'todos',label:'Todas as soluções'},{id:'corporativo',label:'Empresas e condomínios'},{id:'especializado',label:'Limpeza especializada'}].map(item => <button key={item.id} className={filter===item.id ? 'active' : ''} onClick={() => setFilter(item.id)} aria-pressed={filter===item.id}>{item.label}</button>)}</div><motion.div layout className="services"><AnimatePresence mode="popLayout" initial={false}>{services.filter(service => filter === "todos" || service.type === filter).map((service) => <motion.article key={service.name} layout initial={false} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:0.25}} whileHover={reduced ? undefined : {transform:"translateY(-5px)"}} className="service" data-type={service.type}><div className="service-image"><img src={`https://images.unsplash.com/${service.image}?auto=format&fit=crop&w=650&q=80`} width="650" height="450" loading="lazy" alt={service.alt}/><span className="service-number">0{services.indexOf(service) + 1}</span></div><div className="service-body"><p className="eyebrow">{service.tag}</p><h3>{service.name}</h3><p>{service.text}</p><a className="service-link" href="#orcamento" onClick={() => setSelectedService(service.name)}>Quero essa solução <Icon name="arrow" size={20}/></a></div></motion.article>)}</AnimatePresence></motion.div><p className="service-footnote">Precisa cuidar da sua casa ou de um espaço industrial? <a href="#orcamento">Conte o que você precisa →</a></p></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="about" id="sobre"><div className="container about-grid"><div className="about-photo"><img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85" width="900" height="1000" loading="lazy" alt="Espaço corporativo com luz natural e áreas de convivência"/><span className="about-caption"><Icon name="spark"/> Bem-estar começa<br/>com um ambiente bem cuidado.</span></div><div className="about-copy"><p className="eyebrow">O JEITO PRATIC LIMP</p><h2>Mais do que limpar.<br/><span>Cuidar do que<br/>é importante.</span></h2><p>Uma boa primeira impressão. Uma rotina mais organizada. Um espaço onde as pessoas se sentem bem. É para isso que existe a Pratic Limp.</p><div className="benefits">{[{icon:'people',title:'Sua necessidade em primeiro lugar',text:'O ponto de partida é entender seu espaço e sua rotina.'},{icon:'shield',title:'Clareza na contratação',text:'Alinhe escopo, materiais e responsabilidades na proposta.'},{icon:'clock',title:'Uma rotina que faz sentido',text:'Defina a frequência e os horários adequados ao seu ambiente.'},{icon:'chat',title:'Conversa direta',text:'Tire suas dúvidas com quem vai avaliar sua necessidade.'}].map(b => <div key={b.title} className="benefit"><span><Icon name={b.icon}/></span><div><h3>{b.title}</h3><p>{b.text}</p></div></div>)}</div><a className="text-link" href="#orcamento">Vamos conversar sobre seu espaço <Icon name="arrow" size={18}/></a></div></div></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="section container process"><div><p className="eyebrow">SIMPLES, DO PRIMEIRO CONTATO AO CUIDADO</p><h2>Seu próximo passo<br/>é mais tranquilidade.</h2></div><ol><li><span>01</span><h3>Conte o que precisa</h3><p>Informe seu espaço, sua cidade e o serviço que procura.</p></li><li><span>02</span><h3>Alinhe os detalhes</h3><p>Converse sobre frequência, escopo e disponibilidade.</p></li><li><span>03</span><h3>Receba sua proposta</h3><p>Avalie as condições e combine os próximos passos.</p></li></ol></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="faq-section" id="duvidas"><div className="container faq-grid"><div><p className="eyebrow">PODEMOS AJUDAR?</p><h2>Boas respostas.<br/>Decisões tranquilas.</h2><p>Reunimos as principais dúvidas<br/>para facilitar seu primeiro contato.</p><a className="text-link" href="#orcamento">Tenho outra dúvida <Icon name="arrow" size={18}/></a></div><div className="faq-list">{faq.map(([q,a],i)=><details key={q}><summary><span className="faq-number">0{i+1}</span>{q}<span className="plus">+</span></summary><p>{a}</p></details>)}</div></div></motion.section>
<motion.section initial={false} whileInView={reduced ? undefined : {transform:["translateY(16px)","translateY(0px)"]}} viewport={{once:true,amount:0.08}} transition={{duration:0.65,ease:[0.22,1,0.36,1]}} className="section container contact-section" id="orcamento"><div className="contact-copy"><p className="eyebrow">VAMOS CUIDAR DO SEU ESPAÇO?</p><h2>Uma rotina mais leve<br/>começa com<br/><span>uma conversa.</span></h2><p>Conte o que você precisa. Vamos preparar o primeiro passo para uma proposta alinhada ao seu ambiente.</p><a className="contact-line" href={company.phoneHref}><Icon name="phone"/><span><small>Ligue para a Pratic Limp</small>{company.phone}</span></a><a className="contact-line" href={`mailto:${company.email}`}><Icon name="mail"/><span><small>Prefere enviar um e-mail?</small>{company.email}</span></a><div className="coverage"><Icon name="pin"/><p><strong>Consulte nossa cobertura</strong><br/>Informe sua cidade para confirmar o atendimento.</p></div></div><QuoteForm selectedService={selectedService} /></motion.section>
</main>
<footer><div className="container footer-grid"><div><a className="brand" href="#"><span className="brand-mark"><Icon size={29}/></span><span>pratic<span className="brand-light">limp</span><small>LIMPEZA & CONSERVAÇÃO</small></span></a><p>Cuidar do seu espaço.<br/>Simplificar sua rotina.</p></div><div><h3>Explore</h3><a href="#servicos">Nossas soluções</a><a href="#sobre">A Pratic Limp</a><a href="#duvidas">Dúvidas frequentes</a></div><div><h3>Vamos conversar</h3><a href={company.phoneHref}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href="#orcamento">Consultar cobertura de atendimento</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Pratic Limp. Todos os direitos reservados.</span><a href="/privacidade/">Privacidade</a><span>Feito para cuidar.</span></div></footer>
<motion.a whileHover={reduced ? undefined : {scale:1.04}} whileTap={reduced ? undefined : {scale:0.96}} className="floating-contact" href={contact} aria-label={company.whatsapp ? 'Falar com a Pratic Limp no WhatsApp' : 'Falar com a Pratic Limp'}><Icon name="chat" size={25}/><span>Vamos conversar?</span></motion.a>
</MotionConfig>;
}
