import { useEffect, useRef, useState, type ReactNode } from 'react';
import { motion, AnimatePresence, MotionConfig, useReducedMotion, useScroll } from 'motion/react';
import QuoteForm from './components/QuoteForm';
import Icon from './components/Icon';
import { company } from './data/company';
import { services, faq, clients } from './data/content';

const contact = `https://wa.me/${company.whatsapp}?text=${encodeURIComponent('Olá! Quero solicitar um orçamento da Pratic Limp.')}`;
const basePath = import.meta.env.BASE_URL;
const asset = (path:string) => `${basePath}${path.replace(/^\//, '')}`;
function Brand({footer=false}:{footer?:boolean}) {
 return <a className={`brand ${footer?'brand-footer':''}`} href={basePath} aria-label="Pratic Limp — início"><img src={asset('brand/pratic-limp.svg')} width="490" height="290" alt="Pratic Limp"/><span>TERCEIRIZAÇÃO<br/>E LIMPEZA ESPECIALIZADA</span></a>;
}
function Reveal({children,className='',delay=0}:{children:ReactNode;className?:string;delay?:number}) {
 const reduce=useReducedMotion();
 return <motion.div className={className} initial={false} whileInView={reduce?undefined:{transform:['translateY(24px)','translateY(0px)']}} viewport={{once:true,amount:0.12}} transition={{duration:.75,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>;
}
function Privacy(){return <main className="container legal"><a className="text-link" href={basePath}>← Voltar para o site</a><h1>Sua privacidade</h1><p>O formulário prepara uma mensagem no seu navegador. Este site não mantém uma base de solicitações nem envia os dados automaticamente. Você decide enviar a mensagem pelo WhatsApp.</p><h2>Informações de contato</h2><p>Nome, telefone, cidade e detalhes do serviço compõem o pedido de orçamento. Evite incluir dados sensíveis. O aplicativo utilizado possui suas próprias práticas de privacidade.</p><h2>Medição de acesso</h2><p>O site utiliza Google Analytics 4, propriedade G-HTV2EWQWDX, para medir acessos e uso da página. A ferramenta pode processar dados técnicos do dispositivo, navegador, endereço IP e interações de navegação conforme as práticas do Google. Nome, telefone e o conteúdo digitado no orçamento não são enviados intencionalmente ao Analytics.</p><h2>Recursos externos</h2><p>As fontes são carregadas pelo Google Fonts, que pode receber dados técnicos como seu endereço IP. As imagens desta versão são arquivos locais recuperados do site institucional. Meta Pixel e Hotjar não estão ativos.</p><h2>Contato</h2><p>Para dúvidas sobre dados enviados à empresa, entre em contato pelo e-mail <a href={`mailto:${company.email}`}>{company.email}</a>.</p></main>}

export default function App({privacy=false}:{privacy?:boolean}) {
 const [menuOpen,setMenuOpen]=useState(false);
 const [filter,setFilter]=useState('todos');
 const [selectedService,setSelectedService]=useState('');
 const reduced=useReducedMotion();
 const {scrollYProgress}=useScroll();
 const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&menuOpen){setMenuOpen(false);menuButton.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[menuOpen]);
 if(privacy)return <Privacy/>;
 return <MotionConfig reducedMotion="user">
  <a className="skip" href="#conteudo">Pular para o conteúdo</a>
  <div className="topbar"><div className="container"><span><i/> Desde 1991, soluções em limpeza.</span><a href={company.phoneHref}>Vamos conversar: <strong>{company.phone}</strong> <Icon name="arrow" size={13}/></a></div></div>
  <header><div className="container nav"><Brand/><nav id="menu" className={menuOpen?'open':''} aria-label="Navegação principal" onClick={()=>setMenuOpen(false)}><a href="#servicos">Soluções</a><a href="#sobre">Nossa história</a><a href="#clientes">Clientes</a><a href="#duvidas">Dúvidas</a><a className="mobile-menu-cta" href="#orcamento">Solicitar orçamento ↗</a></nav><a className="button header-cta" href="#orcamento">Solicitar orçamento <Icon name="arrow" size={18}/></a><button ref={menuButton} className="menu-toggle" aria-label={menuOpen?'Fechar menu':'Abrir menu'} aria-expanded={menuOpen} aria-controls="menu" onClick={()=>setMenuOpen(!menuOpen)}><span/><span/></button></div>{!reduced&&<motion.div className="reading-progress" style={{scaleX:scrollYProgress}}/>}</header>
  <main id="conteudo">
   <section className="hero"><div className="container hero-grid">
    <Reveal className="hero-copy"><p className="eyebrow"><span className="small-rule"/> PRATIC LIMP · DESDE 1991</p><h1>Limpeza para<br/>sua empresa.<br/><span>Cuidado para<br/>sua rotina.</span></h1><p className="hero-description">Terceirização e limpeza especializada, com profissionais treinados e uniformizados. Para sua empresa e para você.</p><div className="hero-actions"><a className="button button-blue" href="#orcamento">Encontre sua solução <span><Icon name="arrow" size={20}/></span></a><a className="hero-secondary" href={contact}>Falar pelo WhatsApp <Icon name="chat" size={17}/></a></div><div className="hero-footnote"><span className="tiny-logo"><img className="brand-drop" src={asset('brand/pratic-limp-gota.svg')} alt="" width="32" height="32"/></span><p>Transparência, responsabilidade<br/><strong>e compromisso com o seu negócio.</strong></p></div></Reveal>
    <div className="hero-stage"><div className="stage-rings" aria-hidden="true"><span/><span/><span/></div><div className="stage-top"><span>EXPERIÊNCIA QUE<br/>FAZ A DIFERENÇA.</span><img className="brand-drop" src={asset('brand/pratic-limp-gota.svg')} alt="" width="40" height="40"/></div><motion.img initial={false} animate={reduced?undefined:{transform:['translateY(18px)','translateY(0px)']}} transition={{duration:1,ease:[.22,1,.36,1]}} className="hero-business-image" src={asset('brand/terceirizacao.png')} width="472" height="317" fetchPriority="high" alt="Imagem de limpeza de superfície publicada pela Pratic Limp"/><div className="stage-note"><span className="lime-dot"/> PROFISSIONAIS EM LIMPEZA</div><div className="heritage-card"><span>UMA HISTÓRIA<br/>DE CONFIANÇA.</span><strong>1991<span>↗</span></strong><p>O início da nossa atuação<br/>no mercado institucional.</p></div><span className="stage-caption">CUIDAR DO SEU ESPAÇO É O NOSSO TRABALHO.</span></div>
   </div></section>
   <div className="expertise-strip"><div className="container"><span><Icon name="people"/> Equipe treinada e uniformizada</span><span><Icon name="clock"/> Período integral ou meio período</span><span><Icon name="shield"/> Contrato com vigência mensal</span></div></div>
   <section className="clients container" id="clientes"><div className="clients-caption"><p className="eyebrow">RELAÇÕES CONSTRUÍDAS<br/>COM CONFIANÇA.</p><p>Empresas apresentadas<br/>no nosso histórico de clientes.</p></div><div className="client-logos">{clients.map(client=><img key={client.name} src={asset(`brand/${client.file}`)} alt={client.name} width="140" height="70" loading="lazy"/>)}</div></section>
   <section className="solutions section" id="servicos"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow"><span className="section-index">01 /</span> NOSSAS SOLUÇÕES</p><h2>Cada espaço, uma necessidade.<br/><span>Para cada uma, um cuidado.</span></h2></div><p>Da rotina da empresa à limpeza depois da obra.<br/>Conheça os serviços da Pratic Limp.</p></Reveal><div className="filters" role="group" aria-label="Filtrar serviços">{[{id:'todos',label:'Todas as soluções'},{id:'empresarial',label:'Para empresas'},{id:'especializado',label:'Limpeza especializada'}].map(item=><button key={item.id} aria-pressed={filter===item.id} className={filter===item.id?'active':''} onClick={()=>setFilter(item.id)}>{item.label}<span>{item.id==='todos'?'05':item.id==='empresarial'?'02':'03'}</span></button>)}</div><motion.div layout className={`services filter-${filter}`}><AnimatePresence initial={false} mode="popLayout">{services.filter(s=>filter==='todos'||s.category===filter).map(s=><motion.article layout key={s.id} initial={false} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.25}} className={`service ${s.id==='terceirizacao'?'service-featured':''}`}><div className="service-top"><span className="service-number">{s.number}</span><Icon name={s.icon} size={s.id==='terceirizacao'?46:27}/></div><div className="service-content"><p className="eyebrow">{s.tag}</p><h3>{s.name}</h3><p>{s.text}</p>{s.details.length>0&&<ul>{s.details.map(detail=><li key={detail}><Icon name="check" size={16}/>{detail}</li>)}</ul>}</div><a href="#orcamento" className="service-link" aria-label={`Solicitar orçamento: ${s.name}`} onClick={()=>setSelectedService(s.name)}><span>Quero essa solução</span><span className="circle-arrow"><Icon name="arrow" size={20}/></span></a></motion.article>)}</AnimatePresence></motion.div><div className="solutions-bottom"><span>Não sabe qual serviço escolher?</span><a href={contact}>Converse com a Pratic Limp <Icon name="arrow" size={17}/></a></div></div></section>
   <section className="about" id="sobre"><div className="container"><Reveal className="about-grid"><div className="about-title"><p className="eyebrow"><span className="section-index">02 /</span> NOSSA HISTÓRIA</p><h2>Confiança não<br/>se improvisa.<br/><span>Se constrói.</span></h2><div className="since"><span>NO MERCADO<br/>INSTITUCIONAL DESDE</span><strong>1991<span>.</span></strong></div></div><div className="about-copy"><p className="large-copy">Há uma história de <em>comprometimento</em> por trás de cada serviço.</p><p>A Pratic Limp atua no mercado institucional de limpeza desde 1991. Transparência, responsabilidade, agilidade e confiança fazem parte da trajetória da empresa.</p><div className="principles"><div><span>01</span><h3>Nossa missão</h3><p>Fornecer serviços de qualidade aos clientes, respeitando as normas e a natureza.</p></div><div><span>02</span><h3>Nossos valores</h3><p>Comprometimento com os resultados, transparência, responsabilidade e construção de relações duradouras.</p></div></div><a className="text-link" href="#orcamento">Vamos construir essa relação <Icon name="arrow" size={19}/></a></div></Reveal><div className="about-bottom"><span>PROFISSIONALISMO NA EXECUÇÃO.</span><span>RESPONSABILIDADE EM CADA RELAÇÃO.</span><Icon name="spark" size={25}/></div></div></section>
   <section className="commitment section container"><Reveal className="section-heading"><div><p className="eyebrow"><span className="section-index">03 /</span> NOSSO COMPROMISSO</p><h2>Você cuida da sua empresa.<br/><span>A gente cuida da limpeza.</span></h2></div><a className="text-link" href="#orcamento">Solicite uma proposta <Icon name="arrow" size={20}/></a></Reveal><div className="commitment-grid">{[{icon:'people',title:'Gente preparada',text:'Colaboradores uniformizados, treinados e motivados para executar os serviços.'},{icon:'clock',title:'Continuidade no serviço',text:'Substituições em casos de faltas, afastamentos, férias ou solicitação do cliente.'},{icon:'spark',title:'Estrutura para o cuidado',text:'Materiais, produtos e equipamentos para a execução dos serviços de limpeza.'},{icon:'shield',title:'Transparência na relação',text:'Contrato mensal e compromisso com encargos, benefícios e direitos dos colaboradores.'}].map((b,i)=><Reveal className="commitment-item" key={b.title} delay={i*.07}><span className="benefit-icon"><Icon name={b.icon} size={28}/></span><span className="benefit-number">0{i+1}</span><h3>{b.title}</h3><p>{b.text}</p></Reveal>)}</div></section>
   <section className="faq-section" id="duvidas"><div className="container faq-grid"><Reveal><p className="eyebrow"><span className="section-index">04 /</span> ANTES DE CONTRATAR</p><h2>Uma boa conversa<br/>começa com<br/><span>clareza.</span></h2><p>As principais informações para<br/>dar o próximo passo.</p><a href={contact} className="text-link">Tenho outra dúvida <Icon name="arrow" size={18}/></a></Reveal><div className="faq-list">{faq.map(([q,a],i)=><details key={q}><summary><span className="faq-number">0{i+1}</span>{q}<span className="plus">+</span></summary><p>{a}</p></details>)}</div></div></section>
   <section className="contact-section section container" id="orcamento"><Reveal className="contact-copy"><p className="eyebrow"><span className="section-index">05 /</span> VAMOS CONVERSAR</p><h2>O próximo cuidado<br/>começa <span>aqui.</span></h2><p>Conte o que sua empresa ou seu espaço precisa.<br/>Vamos conversar sobre a solução.</p><a className="contact-line" href={company.phoneHref}><Icon name="phone" size={22}/><span><small>TELEFONE E WHATSAPP</small>{company.phone}</span><Icon name="arrow" size={20}/></a><a className="contact-line" href={`mailto:${company.email}`}><Icon name="mail" size={22}/><span><small>E-MAIL</small>{company.email}</span><Icon name="arrow" size={20}/></a><div className="coverage"><Icon name="pin" size={20}/><p>Informe sua cidade para consultar<br/>a disponibilidade de atendimento.</p></div></Reveal><QuoteForm selectedService={selectedService}/></section>
  </main>
  <footer><div className="container footer-main"><div><Brand footer/><p>Terceirização de limpeza<br/>para sua empresa e para você.</p></div><div><h3>Explore</h3><a href="#servicos">Nossas soluções</a><a href="#sobre">Nossa história</a><a href="#clientes">Clientes</a></div><div><h3>Fale com a gente</h3><a href={company.phoneHref}>{company.phone}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href="https://www.facebook.com/praticlimpSP/" target="_blank" rel="noopener noreferrer">Facebook ↗</a></div><a href="#conteudo" className="back-top" aria-label="Voltar ao início">↑</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Pratic Limp.</span><span>DESDE 1991, CUIDANDO DE CADA DETALHE.</span><a href={`${basePath}privacidade/`}>Privacidade</a></div></footer>
  <motion.a className="floating-contact" href={contact} target="_blank" rel="noopener noreferrer" aria-label="Falar com a Pratic Limp no WhatsApp" whileHover={reduced?undefined:{transform:'translateY(-3px)'}} whileTap={reduced?undefined:{scale:.96}}><Icon name="chat" size={23}/><span>Fale por WhatsApp</span></motion.a>
 </MotionConfig>;
}
